site_name: Sematext Documentation
site_url: http://sematext.com/docs
pages:
    - index.md
    - Log Management:
      - Overview: Logs/index.md
      - Logsene and Kibana 4: Logs/Logsene-and-Kibana-4.md
      - Logsene API Reference: Logs/Logsene-API-Reference.md
      - Logsene FAQ: Logs/Logsene-FAQ.md
      - Searching Your Events:
        - Overview: Logs/Searching-Your-Events.md
        - Kibana: Logs/Kibana.md
        - Logsene CLI: Logs/Logsene-CLI.md
        - Search Syntax: Logs/Search-Syntax.md
        - Search through the Elasticsearch API: Logs/Search-through-the-Elasticsearch-API.md
      - Sending Events to Logsene: 
        - Overview: Logs/Sending-Events-to-Logsene.md
        - Index Events via Elasticsearch API: Logs/Index-Events-via-Elasticsearch-API.md
        - Logstash: Logs/Logstash.md
        - Syslog:
          - Overview: Logs/Syslog.md
          - Authorizing IPs for Syslog: Logs/Authorizing-IPs-for-Syslog.md
          - JSON Messages over Syslog: Logs/JSON-Messages-over-Syslog.md
          - rsyslog: Logs/rsyslog.md
          - syslogd: Logs/syslogd.md
          - syslog ng: Logs/syslog-ng.md
        - JSON: Logs/JSON.md
        - X Special Fields: Logs/X-Special-Fields.md
        - Supported Date Formats: Logs/Supported-Date-Formats.md
    - Performance Monitoring:
      - Coda Hale Metrics Reporter: Monitoring/Coda-Hale-Metrics-Reporter.md
      - Custom Metrics: Monitoring/Custom-Metrics.md
      - Database Operations: Monitoring/Database-Operations.md
      - Events Integration: Monitoring/Events-Integration.md
      - Integration:
        - Overview: Monitoring/Integrations.md
        - Alerts - HipChat Integration: Monitoring/Alerts---HipChat-Integration.md
        - Alerts - PagerDuty Integration: Monitoring/Alerts---PagerDuty-Integration.md
        - Alerts - Slack Integration: Monitoring/Alerts---Slack-Integration.md
      - Network Map: Monitoring/Network-Map.md
      - On Demand Profiling: Monitoring/On-Demand-Profiling.md
      - SPM API Reference: Monitoring/SPM-API-Reference.md
      - SPM Client:
        - Overview: Monitoring/SPM-Client.md
        - Chef Recipe: Monitoring/Chef-Recipe.md
        - SPM Monitor - Javaagent: Monitoring/SPM-Monitor---Javaagent.md
        - SPM Monitor - Standalone: Monitoring/SPM-Monitor---Standalone.md
        - SPM Monitor - Switching Modes: Monitoring/SPM-Monitor---Switching-Modes.md
      - SPM FAQ: Monitoring/SPM-FAQ.md
      - SPM for Docker: Monitoring/SPM-for-Docker.md
      - SPM for Hadoop: Monitoring/SPM-for-Hadoop.md
      - SPM for MongoDB: Monitoring/SPM-for-MongoDB.md
      - SPM for Node.js: Monitoring/SPM-for-Node.js.md
      - Tag Support: Monitoring/Tag-Support.md
      - Transaction Tracing: Monitoring/Transaction-Tracing.md
    - Sematext Apps:
      - On Premises: Sematext-Enterprise/On-Premises.md
      - Sematext Apps FAQ: Sematext-Enterprise/Sematext-Apps-FAQ.md
theme: material
theme_dir: custom_theme
repo_url: https://github.com/sematext/docs/
edit_uri: edit/master/docs/
google_analyticsX: ['UA-36723568-3', 'mkdocs.org']
# Options
extra:
  logo: 'images/logo.svg'
  palette:
    primary: 'Indigo'
    accent: 'Indigo'
  font:
    text: 'Roboto,sans-serif'
  social:
    - type: 'github'
      link: 'https://github.com/sematext'
    - type: 'twitter'
      link: 'https://twitter.com/sematext'
    - type: 'linkedin'
      link: 'http://www.linkedin.com/company/sematext-international-llc'
    - type: 'facebook'
      link: 'https://www.facebook.com/Sematext'
    - type: 'google-plus'
      link: 'https://plus.google.com/+SematextGroup'
    - type: 'slideshare'
      link: 'http://slideshare.net/sematext'
    - type: 'feed'
      link: 'http://feeds.feedburner.com/SematextBlog'

extra_css:
  - 'stylesheets/extra.css'
extra_javascript:
  - 'javascripts/extra.js'

    
markdown_extensions:
  - toc(permalink=true)
  - codehilite