site_name: Sematext Documentation
site_url: http://sematext.com/docs
site_favicon: assets/images/favicon.png
pages:
    - Getting Started: index.md
    - Log Management:
      - Overview: logs/index.md
      - Sending Log Events: 
        - Overview: logs/sending-events-to-logsene.md
        - Using Elasticsearch API: logs/index-events-via-elasticsearch-api.md
        - Logstash: logs/logstash.md
        - Syslog:
          - Overview: logs/syslog.md
          - JSON Messages over Syslog: logs/json-messages-over-syslog.md
          - rsyslog: logs/rsyslog.md
          - syslogd: logs/syslogd.md
          - syslog ng: logs/syslog-ng.md
          - Authorizing IPs for Syslog: logs/authorizing-ips-for-syslog.md
        - JSON: logs/json.md
      - Searching Log Events:
        - Overview: logs/searching-your-events.md
        - Logsene CLI: logs/logsene-cli.md
        - Search Syntax: logs/search-syntax.md
        - Using Elasticsearch API: logs/search-through-the-elasticsearch-api.md
        - Kibana Integration: logs/logsene-and-kibana-4.md
        - Kibana: logs/kibana.md
      - API Reference: logs/logsene-api-reference.md
      - Supported Date Formats: logs/supported-date-formats.md
      - Special Fields: logs/special-fields.md
      - FAQ: logs/faq.md
    - Performance Monitoring:
      - Overview: monitoring/index.md
      - Integrations:
        - Overview: monitoring/integrations.md
        - Monitoring Hadoop: monitoring/hadoop.md
        - Monitoring MongoDB: monitoring/mongodb.md
        - Monitoring Node.js: monitoring/node.js.md
        - HipChat: monitoring/alerts-hipchat-integration.md
        - PagerDuty: monitoring/alerts-pagerduty-integration.md
        - Slack: monitoring/alerts-slack-integration.md
      - SPM Client:
        - Overview: monitoring/spm-client.md
        - SPM Monitor - Javaagent: monitoring/spm-monitor-javaagent.md
        - SPM Monitor - Standalone: monitoring/spm-monitor-standalone.md
        - SPM Monitor - Switching Modes: monitoring/spm-monitor-switching-modes.md
        - Chef Recipe: monitoring/chef-recipe.md
      - Events Integration: monitoring/events-integration.md
      - Tag Support: monitoring/tag-support.md
      - Network Map: monitoring/network-map.md
      - Transaction Tracing: monitoring/transaction-tracing.md
      - Database Operations: monitoring/database-operations.md
      - On Demand Profiling: monitoring/on-demand-profiling.md
      - Custom Metrics: monitoring/custom-metrics.md
      - Coda Hale Metrics Reporter: monitoring/coda-hale-metrics-reporter.md
      - API Reference: monitoring/spm-api-reference.md
      - FAQ: monitoring/spm-faq.md
    - Sematext Enterprise:
      - Overview: sematext-enterprise/on-premises.md
      - FAQ: sematext-enterprise/sematext-apps-faq.md
    - Sematext Docker Agent: 
        - Overview: sematext-docker-agent/index.md
        - Installation: sematext-docker-agent/installation.md
        - Configuration: sematext-docker-agent/configuration.md
        - Troubleshooting: sematext-docker-agent/troubleshooting.md

    - Logagent:
      - Overview: logagent/index.md
      - Installation: 
        - Linux & Mac OS X: logagent/installation.md
        - Windows: logagent/installation-windows.md 
        - Heroku: logagent/installation-heroku.md        
      - Usage: 
        - Command Line Parameter: logagent/cli-parameters.md 
        - Configuration file: logagent/config-file.md      
        - Log Parser and pattern definitions: logagent/parser.md
        - Plugins: 
          - Overview: logagent/plugins.md
          - Input plugins: 
            - TCP input: logagent/input-plugin-tcp.md
            - Command input: logagent/input-plugin-command.md
            - Elasticsearch query: logagent/input-plugin-elasticsearch-query.md
            - MSSQL query: logagent/input-plugin-mssql.md
            - MySql query: logagent/input-plugin-mysql.md
            - Postgresql query: logagent/input-plugin-postgresql.md
          - Output plugins: 
            - Elasticsearch: logagent/output-elasticsearch.md
            - Slack webhook: logagent/output-plugin-slack.md
          - Filter plugins: 
            - About filters: logagent/filters.md
            - Grep input filter: logagent/input-filter-grep.md
            - SQL output filter: logagent/output-filter-sql.md
            - Access Watch output filter: logagent/output-filter-accesswatch.md
theme: material
theme_dir: custom_theme
repo_url: https://github.com/sematext/docs/
edit_uri: edit/master/docs/
google_analytics: ['UA-2365268-3', 'mkdocs.org']
site_favicon: 'images/favicon.png'
# Options
extra:
  logo: 'images/logo.svg'
  palette:
    primary: 'Indigo'
    accent: 'Indigo'
  font:
    text: 'Roboto,sans-serif'
  social:
    - type: 'github'
      link: 'https://github.com/sematext'
    - type: 'twitter'
      link: 'https://twitter.com/sematext'
    - type: 'linkedin'
      link: 'https://www.linkedin.com/company/sematext-international-llc'
    - type: 'facebook'
      link: 'https://www.facebook.com/Sematext'
    - type: 'google-plus'
      link: 'https://plus.google.com/+SematextGroup'
    - type: 'slideshare'
      link: 'https://www.slideshare.net/sematext'
    - type: 'feed'
      link: 'http://feeds.feedburner.com/SematextBlog'

extra_css:
  - 'stylesheets/extra.css'
extra_javascript:
  - 'javascripts/extra.js'

    
markdown_extensions:
  - toc(permalink=true)
  - codehilite
