site_name: Sematext Documentation
site_url: http://sematext.com/docs
pages:
    - index.md
    - Log Management:
      - Authorizing IPs for Syslog: PUBLOGSENE/Authorizing-IPs-for-Syslog.md
      - Index Events via Elasticsearch API: PUBLOGSENE/Index-Events-via-Elasticsearch-API.md
      - JSON: PUBLOGSENE/JSON.md
      - JSON Messages over Syslog: PUBLOGSENE/JSON-Messages-over-Syslog.md
      - Kibana: PUBLOGSENE/Kibana.md
      - Logsene and Kibana: PUBLOGSENE/Logsene-and-Kibana-4.md
      - Logsene API Reference: PUBLOGSENE/Logsene-API-Reference.md
      - Logsene Changelog: PUBLOGSENE/Logsene-Changelog.md
      - Logsene CLI: PUBLOGSENE/Logsene-CLI.md
      - Logsene Documentation: PUBLOGSENE/Logsene-Documentation.md
      - Logsene FAQ: PUBLOGSENE/Logsene-FAQ.md
      - Logstash: PUBLOGSENE/Logstash.md
      - rsyslog: PUBLOGSENE/rsyslog.md
      - Searching Your Events: PUBLOGSENE/Searching-Your-Events.md
      - Search Syntax: PUBLOGSENE/Search-Syntax.md
      - Search through the Elasticsearch API: PUBLOGSENE/Search-through-the-Elasticsearch-API.md
      - Sending Events to Logsene: PUBLOGSENE/Sending-Events-to-Logsene.md
      - Supported Date Formats: PUBLOGSENE/Supported-Date-Formats.md
      - Syslog: PUBLOGSENE/Syslog.md
      - syslogd: PUBLOGSENE/syslogd.md
      - syslog ng: PUBLOGSENE/syslog-ng.md
      - X Special Fields: PUBLOGSENE/X-Special-Fields.md
    - Performance Monitoring:
      - Coda Hale Metrics Reporter: PUBSPM/Coda-Hale-Metrics-Reporter.md
      - Custom Metrics: PUBSPM/Custom-Metrics.md
      - Database Operations: PUBSPM/Database-Operations.md
      - Events Integration: PUBSPM/Events-Integration.md
      - Integration:
        - Alerts - HipChat Integration: PUBSPM/Alerts---HipChat-Integration.md
        - Alerts - PagerDuty Integration: PUBSPM/Alerts---PagerDuty-Integration.md
        - Alerts - Slack Integration: PUBSPM/Alerts---Slack-Integration.md
      - Network Map: PUBSPM/Network-Map.md
      - On Demand Profiling: PUBSPM/On-Demand-Profiling.md
      - On Premises Edition: PUBSPM/On-Premises-Edition.md
      - SPM API Reference: PUBSPM/SPM-API-Reference.md
      - SPM Client:
        - Chef Recipe: PUBSPM/Chef-Recipe.md
        - SPM Monitor - Javaagent: PUBSPM/SPM-Monitor---Javaagent.md
        - SPM Monitor - Standalone: PUBSPM/SPM-Monitor---Standalone.md
        - SPM Monitor - Switching Modes: PUBSPM/SPM-Monitor---Switching-Modes.md
      - SPM FAQ: PUBSPM/SPM-FAQ.md
      - SPM for Docker: PUBSPM/SPM-for-Docker.md
      - SPM for Hadoop: PUBSPM/SPM-for-Hadoop.md
      - SPM for MongoDB: PUBSPM/SPM-for-MongoDB.md
      - SPM for Node.js: PUBSPM/SPM-for-Node.js.md
      - Tag Support: PUBSPM/Tag-Support.md
      - Transaction Tracing: PUBSPM/Transaction-Tracing.md
    - Sematext Apps:
      - On Premises: SEMATEXTAPPS/On-Premises.md
      - Sematext Apps: SEMATEXTAPPS/Sematext-Apps.md
      - Sematext Apps FAQ: SEMATEXTAPPS/Sematext-Apps-FAQ.md
theme: material
theme_dir: custom_theme
repo_url: https://github.com/sematext/docs/
edit_uri: edit/master/docs/
google_analyticsX: ['UA-36723568-3', 'mkdocs.org']
# Options
extra:
  logo: 'images/logo.png'
  palette:
    primary: 'Brown'
    accent: 'Indigo'
  font:
    text: 'Roboto,sans-serif'
  social:
    - type: 'github'
      link: 'https://github.com/sematext'
    - type: 'twitter'
      link: 'https://twitter.com/sematext'
    - type: 'linkedin'
      link: 'http://www.linkedin.com/company/sematext-international-llc'
    - type: 'facebook'
      link: 'https://www.facebook.com/Sematext'
    - type: 'google-plus'
      link: 'https://plus.google.com/+SematextGroup'
    - type: 'slideshare'
      link: 'http://slideshare.net/sematext'
    - type: 'feed'
      link: 'http://feeds.feedburner.com/SematextBlog'

extra_css:
  - 'stylesheets/extra.css'
extra_javascript:
  - 'javascripts/extra.js'

    
markdown_extensions:
  - toc(permalink=true)